"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"░▒█░░▒█░▀█▀░▒█▀▄▀█░▒█▀▀▄░▒█▀▀▄
"░░▒█▒█░░▒█░░▒█▒█▒█░▒█▄▄▀░▒█░░░
"░░░▀▄▀░░▄█▄░▒█░░▒█░▒█░▒█░▒█▄▄▀
"	AUTHOR: J. Langedijk
"	DESCRIPTION: .vimrc file
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"SYNTAX AND ENCODING
set number relativenumber	"Relative line numbers
syntax on					"Syntax
scriptencoding utf-8		"Encoding
set encoding=utf-8

"FORMATTING
set smartindent						"Set smart indenting
set linebreak						"Set line breaks
set textwidth=80					"Set textwidth to 80c
set colorcolumn=80					"Draw column 80
set tabstop=4						"<TAB> size
set shiftwidth=4					"< > > size
autocmd BufWritePre * %s/\s\+$//e	"Delete trailing whitespace

"SYSTEM LEVEL THINGS
set nobackup				"No "swp" backup files
set title					"Set terminal title

"CLIPBOARD
nnoremap <C-y> "+y
nnoremap <C-d> "+d
nnoremap <C-p> "+P
set clipboard=unnamedplus	"Default clipboard

"FIND
set wildmenu				"Command line completion
set path+=**				"Fuzzy search

"SHORTCUTS
nnoremap ; :
inoremap [ []<Esc>1hli
inoremap ( ()<Esc>1hli
inoremap { {}<Esc>1hli
autocmd FileType html
	\ inoremap <   <> </><Esc>4hli

"UI/UX
color abstract							"Color sheme
set confirm								"Confirmation message
set nocompatible						"Not BW compatible with vi/ed
nnoremap <S-q> :q!<CR>
nnoremap <Tab> :tabnext<CR>
nnoremap <C-t> :Texplore <CR>
highlight LineNr
	\ ctermfg=white cterm=ITALIC		"Line numbers in italc
highlight CursorLineNr
	\ ctermfg=white cterm=BOLD			"Current line number in bold
noremap <space><space> :set invlist<CR>

"TAB/SPACE VISUALISER MODE
hi SpecialKey ctermfg=Red ctermbg=NONE
set lcs+=space:·
set lcs+=tab:››
set lcs+=eol:¶

"NETrw SETTINGS
let g:netrw_keepdir = 0							"Sync directories
let g:netrw_banner = 0							"Hide banner
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'	"Hide dotfiles

"STORAGE MANAGMENT
set history=1000	"Undo limit

"SPLITS NAVIGATION
noremap <silent> <C-Up> :wincmd k<CR>
noremap <silent> <C-Down> :wincmd j<CR>
noremap <silent> <C-Left> :wincmd h<CR>
noremap <silent> <C-Right> :wincmd l<CR>

"TEMPLATES
command LoadTex		:0r
	\ $HOME/.vim/templates/latex.tex	"Read LaTeX Template
command LoadPython	:0r
	\ $HOME/.vim/templates/python		"Read Python Template
command LoadBash	:0r
	\ $HOME/.vim/templates/bash			"Read bash Template
command LoadLISP	:0r
	\ $HOME/.vim/templates/lisp			"Read LISP Template

"COMPILING
command CompTex2Pdf		!clear &&
	\ pdflatex % && zathura %:r.pdf						"TeX to PDF
command CompLuaTex2Pdf	!clear &&
	\ lualatex % && zathura %:r.pdf						"LuaTeX to PDF
command CompMd2Pdf		!clear &&
	\ pandoc -s % -o %:r.pdf && zathura %:r.pdf			"MD to PDF
command CompMd2Beamer	!clear &&
	\ pandoc -t beamer % -o %:r.pdf && zathura %:r.pdf	"MD to TeX Beamer
command Compile		!clear &&
	\ $HOME/.vim/scripts/compile.sh %
command ConvTex2Md	!clear && pandoc -s % -o %:r.md		"Compile script

"RUN
command RunPython	!clear && python3 %		"Python
command RunMATLAB	!matlab %				"MATLAB(R)
command RunOctave	!octave %				"Octave
command RunLISP		!sbcl --script %		"Common-LISP


"LATEX
autocmd FileType tex,latex inoremap <C-b>   \textbf{}<Esc>hli
autocmd FileType tex,latex inoremap <C-i>   \textit{}<Esc>hli
autocmd filetype tex,latex inoremap <C-t>   \texttt{}<esc>hli
autocmd filetype tex,latex inoremap ;ch     \chapter{}<CR>\label{ch:}<esc>k2li
autocmd filetype tex,latex inoremap ;s1    \section{}<CR>\label{s:}<esc>k2li
autocmd filetype tex,latex inoremap ;s2   \subsection{}<CR>\label{ss:}<esc>k2li
autocmd filetype tex,latex inoremap ;s3
	\ \subsubsection{}<CR>\label{sss:}<esc>k2li
autocmd FileType tex,latex inoremap ;eq
	\ \begin{equation}<CR><CR>\label{eq:}<CR>\tag{}<CR>\end{equation}
	\ <Esc>3ki<Tab>
autocmd FileType tex,latex inoremap ;it
	\ \begin{itemize}<CR><Tab>\item<CR>\end{itemize}<Esc>kA<Space>
autocmd FileType tex,latex inoremap ;cit
	\ \begin{compactitem}<CR><Tab>\item<CR>\end{compactitem}<Esc>kA<Space>
autocmd FileType tex,latex inoremap ;en
	\ \begin{enumerate}<CR><Tab>\item<CR>\end{enumerate}<Esc>kA<Space>
autocmd FileType tex,latex inoremap ;fig
	\ <Esc>:r $HOME/.vim/templates/latexfigure<CR>2j/}<CR>i
autocmd FileType tex,latex inoremap ;up
	\ <Esc>:2r $HOME/.vim/templates/usepackage<CR>/%%END%%<CR>7xi
autocmd FileType tex,latex inoremap $       $$<Esc>1hli
autocmd FileType tex,latex inoremap ;bg     \begin{}<CR>\end{}
autocmd FileType tex,latex nnoremap <S-c>   <Esc>:CompTex2Pdf<CR>
autocmd FileType tex,latex nnoremap <C-s>
	\ <Esc>:setlocal spell spelllang=en_us<CR>

"MARKDOWN
autocmd FileType md,markdown inoremap <C-b>		****<Esc>2hli
autocmd filetype md,markdown inoremap <C-t>		``<esc>hli
autocmd filetype md,markdown inoremap <C-s>		#<Space>
autocmd FileType md,markdown inoremap ;l		[]()<Esc>3hli
autocmd FileType md,markdown inoremap ;eq		$$<CR><CR>$$<Esc>ki<Tab>
autocmd FileType md,markdown inoremap ;fig
	\ ![Caption\label{fig:figure}]()<Esc>1hli
autocmd FileType md,markdown inoremap $			$$<Esc>1hli
autocmd FileType md,markdown nnoremap <S-c>		<Esc>:CompMd2Pdf<CR>
autocmd FileType md,markdown nnoremap <S-b>		<Esc>:CompMd2Beamer<CR>
autocmd FileType md,markdown nnoremap <C-s>
	\ <Esc>:setlocal spell spelllang=en_us<CR>

"PYTHON
autocmd FileType python inoremap	;def
	\ def method(args) -> None :<CR><Tab>
autocmd FileType python inoremap	;class
	\ class cl(args) -> None:<CR><Tab>def _init_(args) -> None:<CR><Tab><Tab>

"LISP
autocmd FileType lisp,clisp inoremap	<CR>   <CR>()<Esc>1hli
autocmd FileType lisp,clisp inoremap	'      '()<Esc>1hli
autocmd FileType lisp,clisp inoremap	;      ;;
